CREATE TABLE SC_EXAMINATION
(
  EXAMINATION_ID       NUMBER                   NOT NULL,
  EXAMINATION_NAME     VARCHAR2(2000 CHAR),
  MAXIMUM_MARKS        NUMBER,
  NUMBER_OF_QUESTIONS  NUMBER,
  MARKS_PER_QUESTION   NUMBER,
  PASSING_MARKS        NUMBER,
  NEGATIVE_MARKS       NUMBER                   DEFAULT 0,
  TIME_IN_MINUTES      NUMBER,
  CREATED_BY           NUMBER,
  CREATED_DATE         DATE
);


CREATE TABLE SC_QUESTION
(
  QUESTION_ID     NUMBER                        NOT NULL,
  QUESTION_ORDER  NUMBER                        NOT NULL,
  QUESTION        VARCHAR2(4000 CHAR),
  OPTION_A        VARCHAR2(2000 CHAR),
  OPTION_B        VARCHAR2(2000 CHAR),
  OPTION_C        VARCHAR2(2000 CHAR),
  OPTION_D        VARCHAR2(2000 CHAR),
  CORRECT_ANSWER  CHAR(1 CHAR)                  NOT NULL,
  EXAMINATION_ID  NUMBER                        NOT NULL
);


CREATE TABLE SC_RESULT
(
  RESULT_ID         NUMBER                      NOT NULL,
  EXAMINATION_ID    NUMBER,
  USER_ID           NUMBER,
  NUMBER_CORRECT    NUMBER,
  NUMBER_INCORRECT  NUMBER,
  MARKS_OBTAINED    NUMBER,
  IS_PASS           NUMBER,
  EXAMINATION_DATE  DATE                        NOT NULL
);


CREATE TABLE SC_ROLE
(
  ROLE_ID  NUMBER,
  ROLE     VARCHAR2(50 CHAR)                    NOT NULL
);


CREATE TABLE SC_USER
(
  USER_ID     NUMBER,
  USER_NAME   VARCHAR2(50 CHAR),
  FIRST_NAME  VARCHAR2(50 CHAR),
  LAST_NAME   VARCHAR2(50 CHAR),
  ADDRESS     VARCHAR2(2000 CHAR),
  CONTACT     VARCHAR2(15 CHAR),
  EMAIL       VARCHAR2(100 CHAR),
  PASSWORD    VARCHAR2(50 CHAR),
  ACTIVE      NUMBER,
  ROLE_ID     NUMBER
);


CREATE UNIQUE INDEX ROLE_PK ON SC_ROLE
(ROLE_ID);


CREATE UNIQUE INDEX SC_EXAMINATION_PK ON SC_EXAMINATION
(EXAMINATION_ID);


CREATE INDEX SC_EXAM_USER_FK_IDX ON SC_EXAMINATION
(CREATED_BY);


CREATE UNIQUE INDEX SC_QUESTION_PK ON SC_QUESTION
(QUESTION_ID);


CREATE INDEX SC_QUES_EXAM_FK_IDX ON SC_QUESTION
(EXAMINATION_ID);


CREATE UNIQUE INDEX SC_RESULT_PK ON SC_RESULT
(RESULT_ID);


CREATE INDEX SC_RSLT_EXAM_FK_IDX ON SC_RESULT
(EXAMINATION_ID);


CREATE INDEX SC_RSLT_USER_FK_IDX ON SC_RESULT
(USER_ID);


CREATE UNIQUE INDEX USERS_PK ON SC_USER
(USER_ID);


CREATE UNIQUE INDEX USERS_UK ON SC_USER
(USER_NAME);


CREATE INDEX USER_ROLE_FK_IDX ON SC_USER
(ROLE_ID);


ALTER TABLE SC_EXAMINATION ADD (
  CONSTRAINT SC_EXAMINATION_PK
  PRIMARY KEY
  (EXAMINATION_ID)
  USING INDEX SC_EXAMINATION_PK
  ENABLE VALIDATE);

ALTER TABLE SC_QUESTION ADD (
  CONSTRAINT SC_QUESTION_PK
  PRIMARY KEY
  (QUESTION_ID)
  USING INDEX SC_QUESTION_PK
  ENABLE VALIDATE);

ALTER TABLE SC_RESULT ADD (
  CONSTRAINT SC_RESULT_PK
  PRIMARY KEY
  (RESULT_ID)
  USING INDEX SC_RESULT_PK
  ENABLE VALIDATE);

ALTER TABLE SC_ROLE ADD (
  CONSTRAINT ROLE_PK
  PRIMARY KEY
  (ROLE_ID)
  USING INDEX ROLE_PK
  ENABLE VALIDATE);

ALTER TABLE SC_USER ADD (
  CONSTRAINT SC_USER_PK
  PRIMARY KEY
  (USER_ID)
  USING INDEX USERS_PK
  ENABLE VALIDATE,
  CONSTRAINT USERS_UK
  UNIQUE (USER_NAME)
  USING INDEX USERS_UK
  ENABLE VALIDATE);

ALTER TABLE SC_EXAMINATION ADD (
  CONSTRAINT SC_EXAM_USER_FK 
  FOREIGN KEY (CREATED_BY) 
  REFERENCES SC_USER (USER_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE SC_QUESTION ADD (
  CONSTRAINT SC_QUES_EXAM_FK 
  FOREIGN KEY (EXAMINATION_ID) 
  REFERENCES SC_EXAMINATION (EXAMINATION_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE SC_RESULT ADD (
  CONSTRAINT SC_RESULT_EXAM_FK 
  FOREIGN KEY (EXAMINATION_ID) 
  REFERENCES SC_EXAMINATION (EXAMINATION_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SC_RESULT_USER_FK 
  FOREIGN KEY (USER_ID) 
  REFERENCES SC_USER (USER_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE SC_USER ADD (
  CONSTRAINT SC_USER_ROLE_FK 
  FOREIGN KEY (ROLE_ID) 
  REFERENCES SC_ROLE (ROLE_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

CREATE SEQUENCE SC_ROLE_SEQ
  MINVALUE 1
  MAXVALUE 999999999
  START WITH 1
  INCREMENT BY 1;
  
CREATE SEQUENCE SC_USER_SEQ
  MINVALUE 1
  MAXVALUE 999999999
  START WITH 1
  INCREMENT BY 1;  
  
CREATE SEQUENCE SC_EXAMINATION_SEQ
  MINVALUE 1
  MAXVALUE 999999999
  START WITH 1
  INCREMENT BY 1;  
  
CREATE SEQUENCE SC_QUESTION_SEQ
  MINVALUE 1
  MAXVALUE 999999999
  START WITH 1
  INCREMENT BY 1;
  
CREATE SEQUENCE SC_RESULT_SEQ
  MINVALUE 1
  MAXVALUE 999999999
  START WITH 1
  INCREMENT BY 1;